import { PT_Sans } from "next/font/google";
import "./../styles/main.scss";
import Header from "@/components/Header/Header";

const ptSans = PT_Sans({
	variable: "--font-main",
	subsets: ["latin", "cyrillic"],
	weight: ["400", "700"],
	style: ["normal", "italic"],
	display: "swap",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className={ptSans.variable}>
			<body>
				<Header />
				{children}
			</body>
		</html>
	);
}
